export const columnsDashBoardSUI = [
    { head: "Id", body: "APSID" },
    { head: "APS", body: "APSNOM" },
    { head: "F19", body: "F19" },
    { head: "F23", body: "F23" },
    { head: "F24", body: "F24" },
    { head: "F35", body: "F35" },
    { head: "F36", body: "F36" },
    { head: "Usuario", body: "USUARIO" },
];

export const columsF19 = [
    { head: "NJ", body: "F19_NJ" },
    { head: "NDJ", body: "F19_NDJ" },
    { head: "CRTJ", body: "F19_CRTJ" },
    { head: "CDFJ", body: "F19_CDFJ" },
    { head: "QRTJ", body: "F19_QRTJ" },
    { head: "QRJ", body: "F19_QRJ" },
    { head: "QBLJ", body: "F19_QBLJ" },
    { head: "QLUJ", body: "F19_QLUJ" },
    { head: "QNAZ", body: "F19_QNAZ" },
    { head: "QAJ", body: "F19_QAJ" },
];

export const columsF23 = [
    { head: "Empresas", body: "EMPR_EMPR" },
    { head: "IDNOMAPS", body: "F23_ID" },
    { head: "NUAP", body: "F23_NUAP" },
    { head: "N", body: "F23_N" },
    { head: "CP", body: "F23_CP" },
    { head: "CCC", body: "F23_CCC" },
    { head: "M2CCJ", body: "F23_M2CCJ" },
    { head: "CLAVJ", body: "F23_CLAVJ" },
    { head: "M3AGUAJ", body: "F23_M3AGUAJ" },
    { head: "M2LAVJ", body: "F23_M2LAVJ" },
    { head: "CLPJ", body: "F23_CLPJ" },
    { head: "KLPJ", body: "F23_KLPJ" },
    { head: "CCEI", body: "F23_CCEI" },
    { head: "TIJ", body: "F23_TIJ" },
    { head: "CCEMJ", body: "F23_CCEMJ" },
    { head: "TMJ", body: "F23_TMJ" },
    { head: "CLUS", body: "F23_CLUS" },
    { head: "CBLJ", body: "F23_CBLJ" },
    { head: "LBLJ", body: "F23_LBLJ" },
    { head: "CBLS", body: "F23_CBLS" },
    { head: "FACBLCLUS", body: "F23_FACBLCLUS" },
    { head: "ABC", body: "F23_ABC" },
];

export const columsF24 = [
    { head: "NUAP", body: "F24_NUAP" },
    { head: "NUSD", body: "F24_NUSD" },
    { head: "CENTROIDE", body: "F24_CENTROIDE" },
    { head: "QRT", body: "F24_QRT" },
    { head: "F1", body: "F24_F1" },
    { head: "F2", body: "F24_F2" },
    { head: "CPE", body: "F24_CPE" },
    { head: "PRTZ", body: "F24_PRTZ" },
    { head: "DET", body: "F24_DET" },
    { head: "F1ET", body: "F24_F1ET" },
    { head: "CPEET", body: "F24_CPEET" },
    { head: "PRTZET", body: "F24_PRTZET" },
    { head: "CEG", body: "F24_CEG" },
    { head: "CRTP", body: "F24_CRTP" },
    { head: "SALINIDAD", body: "F24_SALINIDAD" },
    { head: "VACRTABC", body: "F24_VACRTABC" },
    { head: "VACRT", body: "F24_VACRT" },
    { head: "FCK", body: "F24_FCK" },
    { head: "T", body: "F24_T" },
    { head: "CRTZ", body: "F24_CRTZ" },
    { head: "CRT", body: "F24_CRT" },
    { head: "FACRT", body: "F24_FACRT" },
    { head: "FACCS", body: "F24_FACCS" },
];

export const columsF35 = [
    { head: "NUSD", body: "F35_NUSD" },
    { head: "NOMDF", body: "F35_NOMDF" },
    { head: "CAMRERS", body: "F35_CAMRERS" },
    { head: "QRSMES", body: "F35_QRSMES" },
    { head: "QRSPROM", body: "F35_QRSPROM" },
    { head: "CDFVU", body: "F35_CDFVU" },
    { head: "PERADDT", body: "F35_PERADDT" },
    { head: "CDFPC", body: "F35_CDFPC" },
    { head: "INCENTIVO", body: "F35_INCENTIVO" },
    { head: "DISPALT9", body: "F35_DISPALT9" },
    { head: "INCCDFALT9", body: "F35_INCCDFALT9" },
    { head: "VACDFABC", body: "F35_VACDFABC" },
    { head: "VACDF", body: "F35_VACDF" },
    { head: "PRCTCRRCP", body: "F35_PRCTCRRCP" },
    { head: "CDF", body: "F35_CDF" },
    { head: "CDFP", body: "F35_CDFP" },
    { head: "FACCDF", body: "F35_FACCDF" },
    { head: "V0", body: "F35_V0" },
    { head: "VM", body: "F35_VM" },
    { head: "MCRS", body: "F35_MCRS" },
    { head: "ICRSM", body: "F35_ICRSM" },
    { head: "ICCRS", body: "F35_ICCRS" },
    { head: "FREIN", body: "F35_FREIN" },
    { head: "CAPREMDF", body: "F35_CAPREMDF" },
];

export const columsF36 = [
    { head: "NUSD", body: "F36_NUSD" },
    { head: "NOMDPTO", body: "F36_NOMDPTO" },
    { head: "NOMMPIO", body: "F36_NOMMPIO" },
    { head: "NOMDF", body: "F36_NOMDF" },
    { head: "VLMES", body: "F36_VLMES" },
    { head: "VLMPROM", body: "F36_VLMPROM" },
    { head: "ESCENA", body: "F36_ESCENA" },
    { head: "CTLMVU", body: "F36_CTLMVU" },
    { head: "ANNOPOSCLA", body: "F36_ANNOPOSCLA" },
    { head: "CTLMPC", body: "F36_CTLMPC" },
    { head: "CTLM", body: "F36_CTLM" },
    { head: "CTLMX", body: "F36_CTLMX" },
    { head: "VACTLABC", body: "F36_VACTLABC" },
    { head: "VACTL", body: "F36_VACTL" },
    { head: "FCKCTL", body: "F36_FCKCTL" },
    { head: "QRS", body: "F36_QRS" },
    { head: "CTL", body: "F36_CTL" },
    { head: "FACCTL", body: "F36_FACCTL" },
];

export const columnsFormulario19 = [
    { head: "AÑO", body: "F19_ANNO" },
    { head: "MES", body: "F19_MES" },
    { head: "NJ", body: "F19_NJ" },
    { head: "NDJ", body: "F19_NDJ" },
    { head: "CRTJ", body: "F19_CRTJ" },
    { head: "CDFJ", body: "F19_CDFJ" },
    { head: "QRTJ", body: "F19_QRTJ" },
    { head: "QRJ", body: "F19_QRJ" },
    { head: "QBLJ", body: "F19_QBLJ" },
    { head: "QLUJ", body: "F19_QLUJ" },
    { head: "QNAZ", body: "F19_QNAZ" },
    { head: "QAJ", body: "F19_QAJ" },
];

export const formatoFormulario19 = {
    "F19_ANNO": { name: "AÑO", filtre: true },
    "F19_MES": { name: "MES", filtre: false },
    "F19_NJ": { name: "NJ", filtre: false},
    "F19_NDJ": { name: "NDJ", filtre: false},
    "F19_CRTJ": { name: "CRTJ", filtre: false},
    "F19_CDFJ": { name: "CDFJ", filtre: false},
    "F19_QRTJ": { name: "QRTJ", filtre: false},
    "F19_QRJ": { name: "QRJ", filtre: false},
    "F19_QBLJ": { name: "QBLJ", filtre: false},
    "F19_QLUJ": { name: "QLUJ", filtre: false},
    "F19_QNAZ": { name: "QNAZ", filtre: false},
    "F19_QAJ": { name: "QAJ", filtre: false},
};

export const columnsFormulario23 = [
    { head: "AÑO", body: "F23_ANNO" },
    { head: "MES", body: "F23_MES" },
    { head: "EMPRESAS", body: "EMPR_EMPR" },
    { head: "IDNOMAPS", body: "F23_ID" },
    { head: "NUAP", body: "F23_NUAP" },
    { head: "N", body: "F23_N" },
    { head: "CP", body: "F23_CP" },
    { head: "CCC", body: "F23_CCC" },
    { head: "M2CCJ", body: "F23_M2CCJ" },
    { head: "CLAVJ", body: "F23_CLAVJ" },
    { head: "M3AGUAJ", body: "F23_M3AGUAJ" },
    { head: "M2LAVJ", body: "F23_M2LAVJ" },
    { head: "CLPJ", body: "F23_CLPJ" },
    { head: "KLPJ", body: "F23_KLPJ" },
    { head: "CCEI", body: "F23_CCEI" },
    { head: "TIJ", body: "F23_TIJ" },
    { head: "CCEMJ", body: "F23_CCEMJ" },
    { head: "TMJ", body: "F23_TMJ" },
    { head: "CLUS", body: "F23_CLUS" },
    { head: "CBLJ", body: "F23_CBLJ" },
    { head: "LBLJ", body: "F23_LBLJ" },
    { head: "CBLS", body: "F23_CBLS" },
    { head: "FACBLCLUS", body: "F23_FACBLCLUS" },
    { head: "ABC", body: "F23_ABC" },
];

export const formatoFormulario23 = {
    "F23_ANNO": { name: "AÑO", filtre: true },
    "F23_MES": { name: "MES", filtre: false },
    "EMPR_EMPR": { name: "EMPRESAS", filtre: false },
    "F23_ID": { name: "IDNOMAPS", filtre: false },
    "F23_NUAP": { name: "NUAP", filtre: false },
    "F23_N": { name: "N", filtre: false },
    "F23_CP": { name: "CP", filtre: false },
    "F23_CCC": { name: "CCC", filtre: false },
    "F23_M2CCJ": { name: "M2CCJ", filtre: false },
    "F23_CLAVJ": { name: "CLAVJ", filtre: false },
    "F23_M3AGUAJ": { name: "M3AGUAJ", filtre: false },
    "F23_M2LAVJ": { name: "M2LAVJ", filtre: false },
    "F23_CLPJ": { name: "CLPJ", filtre: false },
    "F23_KLPJ": { name: "KLPJ", filtre: false },
    "F23_CCEI": { name: "CCEI", filtre: false },
    "F23_TIJ": { name: "TIJ", filtre: false },
    "F23_CCEMJ": { name: "CCEMJ", filtre: false },
    "F23_TMJ": { name: "TMJ", filtre: false },
    "F23_CLUS": { name: "CLUS", filtre: false },
    "F23_CBLJ": { name: "CBLJ", filtre: false },
    "F23_LBLJ": { name: "LBLJ", filtre: false },
    "F23_CBLS": { name: "CBLS", filtre: false },
    "F23_FACBLCLUS": { name: "FACBLCLUS", filtre: false },
    "F23_ABC": { name: "ABC", filtre: false },
};

export const columnsFormulario24 = [
    { head: "AÑO", body: "F24_ANNO" },
    { head: "MES", body: "F24_MES" },
    { head: "NUAP", body: "F24_NUAP" },
    { head: "NUSD", body: "F24_NUSD" },
    { head: "CENTROIDE", body: "F24_CENTROIDE" },
    { head: "QRT", body: "F24_QRT" },
    { head: "F1", body: "F24_F1" },
    { head: "F2", body: "F24_F2" },
    { head: "CPE", body: "F24_CPE" },
    { head: "PRTZ", body: "F24_PRTZ" },
    { head: "DET", body: "F24_DET" },
    { head: "F1ET", body: "F24_F1ET" },
    { head: "CPEET", body: "F24_CPEET" },
    { head: "PRTZET", body: "F24_PRTZET" },
    { head: "CEG", body: "F24_CEG" },
    { head: "CRTP", body: "F24_CRTP" },
    { head: "SALINIDAD", body: "F24_SALINIDAD" },
    { head: "VACRTABC", body: "F24_VACRTABC" },
    { head: "VACRT", body: "F24_VACRT" },
    { head: "FCK", body: "F24_FCK" },
    { head: "T", body: "F24_T" },
    { head: "CRTZ", body: "F24_CRTZ" },
    { head: "CRT", body: "F24_CRT" },
    { head: "FACRT", body: "F24_FACRT" },
    { head: "FACCS", body: "F24_FACCS" },
];

export const formatoFormulario24 = {
    "F24_ANNO": { name: "AÑO", filtre: true },
    "F24_MES": { name: "MES", filtre: false },
    "F24_NUAP": { name: "NUAP", filtre: false },
    "F24_NUSD": { name: "NUSD", filtre: false },
    "F24_CENTROIDE": { name: "CENTROIDE", filtre: false },
    "F24_QRT": { name: "QRT", filtre: false },
    "F24_F1": { name: "F1", filtre: false },
    "F24_F2": { name: "F2", filtre: false },
    "F24_CPE": { name: "CPE", filtre: false },
    "F24_PRTZ": { name: "PRTZ", filtre: false },
    "F24_DET": { name: "DET", filtre: false },
    "F24_F1ET": { name: "F1ET", filtre: false },
    "F24_CPEET": { name: "CPEET", filtre: false },
    "F24_PRTZET": { name: "PRTZET", filtre: false },
    "F24_CEG": { name: "CEG", filtre: false },
    "F24_CRTP": { name: "CRTP", filtre: false },
    "F24_SALINIDAD": { name: "SALINIDAD", filtre: false },
    "F24_VACRTABC": { name: "VACRTABC", filtre: false },
    "F24_VACRT": { name: "VACRT", filtre: false },
    "F24_FCK": { name: "FCK", filtre: false },
    "F24_T": { name: "T", filtre: false },
    "F24_CRTZ": { name: "CRTZ", filtre: false },
    "F24_CRT": { name: "CRT", filtre: false },
    "F24_FACRT": { name: "FACRT", filtre: false },
    "F24_FACCS": { name: "FACCS", filtre: false },
};

export const columnsFormulario35 = [
    { head: "AÑO", body: "F35_ANNO" },
    { head: "MES", body: "F35_MES" },
    { head: "NUSD", body: "F35_NUSD" },
    { head: "NOMDF", body: "F35_NOMDF" },
    { head: "CAMRERS", body: "F35_CAMRERS" },
    { head: "QRSMES", body: "F35_QRSMES" },
    { head: "QRSPROM", body: "F35_QRSPROM" },
    { head: "CDFVU", body: "F35_CDFVU" },
    { head: "PERADDT", body: "F35_PERADDT" },
    { head: "CDFPC", body: "F35_CDFPC" },
    { head: "INCENTIVO", body: "F35_INCENTIVO" },
    { head: "DISPALT9", body: "F35_DISPALT9" },
    { head: "INCCDFALT9", body: "F35_INCCDFALT9" },
    { head: "VACDFABC", body: "F35_VACDFABC" },
    { head: "VACDF", body: "F35_VACDF" },
    { head: "PRCTCRRCP", body: "F35_PRCTCRRCP" },
    { head: "CDF", body: "F35_CDF" },
    { head: "CDFP", body: "F35_CDFP" },
    { head: "FACCDF", body: "F35_FACCDF" },
    { head: "V0", body: "F35_V0" },
    { head: "VM", body: "F35_VM" },
    { head: "MCRS", body: "F35_MCRS" },
    { head: "ICRSM", body: "F35_ICRSM" },
    { head: "ICCRS", body: "F35_ICCRS" },
    { head: "FREIN", body: "F35_FREIN" },
    { head: "CAPREMDF", body: "F35_CAPREMDF" },
];

export const formatoFormulario35 = {
    "F35_ANNO": { name: "AÑO", filtre: true },
    "F35_MES": { name: "MES", filtre: false },
    "F35_NUSD": { name: "NUSD", filtre: false },
    "F35_NOMDF": { name: "NOMDF", filtre: false },
    "F35_CAMRERS": { name: "CAMRERS", filtre: false },
    "F35_QRSMES": { name: "QRSMES", filtre: false },
    "F35_QRSPROM": { name: "QRSPROM", filtre: false },
    "F35_CDFVU": { name: "CDFVU", filtre: false },
    "F35_PERADDT": { name: "PERADDT", filtre: false },
    "F35_CDFPC": { name: "CDFPC", filtre: false },
    "F35_INCENTIVO": { name: "INCENTIVO", filtre: false },
    "F35_DISPALT9": { name: "DISPALT9", filtre: false },
    "F35_INCCDFALT9": { name: "INCCDFALT9", filtre: false },
    "F35_VACDFABC": { name: "VACDFABC", filtre: false },
    "F35_VACDF": { name: "VACDF", filtre: false },
    "F35_PRCTCRRCP": { name: "PRCTCRRCP", filtre: false },
    "F35_CDF": { name: "CDF", filtre: false },
    "F35_CDFP": { name: "CDFP", filtre: false },
    "F35_FACCDF": { name: "FACCDF", filtre: false },
    "F35_V0": { name: "V0", filtre: false },
    "F35_VM": { name: "VM", filtre: false },
    "F35_MCRS": { name: "MCRS", filtre: false },
    "F35_ICRSM": { name: "ICRSM", filtre: false },
    "F35_ICCRS": { name: "ICCRS", filtre: false },
    "F35_FREIN": { name: "FREIN", filtre: false },
    "F35_CAPREMDF": { name: "CAPREMDF", filtre: false },
};

export const columnsFormulario36 = [
    { head: "AÑO", body: "F36_ANNO" },
    { head: "MES", body: "F36_MES" },
    { head: "NUSD", body: "F36_NUSD" },
    { head: "NOMDPTO", body: "F36_NOMDPTO" },
    { head: "NOMMPIO", body: "F36_NOMMPIO" },
    { head: "NOMDF", body: "F36_NOMDF" },
    { head: "VLMES", body: "F36_VLMES" },
    { head: "VLMPROM", body: "F36_VLMPROM" },
    { head: "ESCENA", body: "F36_ESCENA" },
    { head: "CTLMVU", body: "F36_CTLMVU" },
    { head: "ANNOPOSCLA", body: "F36_ANNOPOSCLA" },
    { head: "CTLMPC", body: "F36_CTLMPC" },
    { head: "CTLM", body: "F36_CTLM" },
    { head: "CTLMX", body: "F36_CTLMX" },
    { head: "VACTLABC", body: "F36_VACTLABC" },
    { head: "VACTL", body: "F36_VACTL" },
    { head: "FCKCTL", body: "F36_FCKCTL" },
    { head: "QRS", body: "F36_QRS" },
    { head: "CTL", body: "F36_CTL" },
    { head: "FACCTL", body: "F36_FACCTL" },
];

export const formatoFormulario36 = {
    "F36_ANNO": { name: "AÑO", filtre: true },
    "F36_MES": { name: "MES", filtre: false },
    "F36_NUSD": { name: "NUSD", filtre: false },
    "F36_NOMDPTO": { name: "NOMDPTO", filtre: false },
    "F36_NOMMPIO": { name: "NOMMPIO", filtre: false },
    "F36_NOMDF": { name: "NOMDF", filtre: false },
    "F36_VLMES": { name: "VLMES", filtre: false },
    "F36_VLMPROM": { name: "VLMPROM", filtre: false },
    "F36_ESCENA": { name: "ESCENA", filtre: false },
    "F36_CTLMVU": { name: "CTLMVU", filtre: false },
    "F36_ANNOPOSCLA": { name: "ANNOPOSCLA", filtre: false },
    "F36_CTLMPC": { name: "CTLMPC", filtre: false },
    "F36_CTLM": { name: "CTLM", filtre: false },
    "F36_CTLMX": { name: "CTLMX", filtre: false },
    "F36_VACTLABC": { name: "VACTLABC", filtre: false },
    "F36_VACTL": { name: "VACTL", filtre: false },
    "F36_FCKCTL": { name: "FCKCTL", filtre: false },
    "F36_QRS": { name: "QRS", filtre: false },
    "F36_CTL": { name: "CTL", filtre: false },
    "F36_FACCTL": { name: "FACCTL", filtre: false },
};

export const columnsRevFormato19 = [
    { head: "REVE ID", body: "REVE_ID" },
    { head: "AÑO", body: "F19_ANNO" },
    { head: "MES", body: "F19_MES" },
    { head: "NJ", body: "F19_NJ" },
    { head: "NDJ", body: "F19_NDJ" },
    { head: "CRTJ", body: "F19_CRTJ" },
    { head: "CDFJ", body: "F19_CDFJ" },
    { head: "QRTJ", body: "F19_QRTJ" },
    { head: "QRJ", body: "F19_QRJ" },
    { head: "QBLJ", body: "F19_QBLJ" },
    { head: "QLUJ", body: "F19_QLUJ" },
    { head: "QNAZ", body: "F19_QNAZ" },
    { head: "QAJ", body: "F19_QAJ" },
];

export const columnsRevFormato23 = [
    { head: "REVE ID", body: "REVE_ID" },
    { head: "AÑO", body: "F23_ANNO" },
    { head: "MES", body: "F23_MES" },
    { head: "EMPRESAS", body: "EMPR_EMPR" },
    { head: "IDNOMAPS", body: "F23_ID" },
    { head: "NUAP", body: "F23_NUAP" },
    { head: "N", body: "F23_N" },
    { head: "CP", body: "F23_CP" },
    { head: "CCC", body: "F23_CCC" },
    { head: "M2CCJ", body: "F23_M2CCJ" },
    { head: "CLAVJ", body: "F23_CLAVJ" },
    { head: "M3AGUAJ", body: "F23_M3AGUAJ" },
    { head: "M2LAVJ", body: "F23_M2LAVJ" },
    { head: "CLPJ", body: "F23_CLPJ" },
    { head: "KLPJ", body: "F23_KLPJ" },
    { head: "CCEI", body: "F23_CCEI" },
    { head: "TIJ", body: "F23_TIJ" },
    { head: "CCEMJ", body: "F23_CCEMJ" },
    { head: "TMJ", body: "F23_TMJ" },
    { head: "CLUS", body: "F23_CLUS" },
    { head: "CBLJ", body: "F23_CBLJ" },
    { head: "LBLJ", body: "F23_LBLJ" },
    { head: "CBLS", body: "F23_CBLS" },
    { head: "FACBLCLUS", body: "F23_FACBLCLUS" },
    { head: "ABC", body: "F23_ABC" },
];

export const columnsRevFormato24 = [
    { head: "REVE ID", body: "REVE_ID" },
    { head: "AÑO", body: "F24_ANNO" },
    { head: "MES", body: "F24_MES" },
    { head: "NUAP", body: "F24_NUAP" },
    { head: "NUSD", body: "F24_NUSD" },
    { head: "CENTROIDE", body: "F24_CENTROIDE" },
    { head: "QRT", body: "F24_QRT" },
    { head: "F1", body: "F24_F1" },
    { head: "F2", body: "F24_F2" },
    { head: "CPE", body: "F24_CPE" },
    { head: "PRTZ", body: "F24_PRTZ" },
    { head: "DET", body: "F24_DET" },
    { head: "F1ET", body: "F24_F1ET" },
    { head: "CPEET", body: "F24_CPEET" },
    { head: "PRTZET", body: "F24_PRTZET" },
    { head: "CEG", body: "F24_CEG" },
    { head: "CRTP", body: "F24_CRTP" },
    { head: "SALINIDAD", body: "F24_SALINIDAD" },
    { head: "VACRTABC", body: "F24_VACRTABC" },
    { head: "VACRT", body: "F24_VACRT" },
    { head: "FCK", body: "F24_FCK" },
    { head: "T", body: "F24_T" },
    { head: "CRTZ", body: "F24_CRTZ" },
    { head: "CRT", body: "F24_CRT" },
    { head: "FACRT", body: "F24_FACRT" },
    { head: "FACCS", body: "F24_FACCS" },
];

export const columnsRevFormato35 = [
    { head: "REVE ID", body: "REVE_ID" },
    { head: "AÑO", body: "F35_ANNO" },
    { head: "MES", body: "F35_MES" },
    { head: "NUSD", body: "F35_NUSD" },
    { head: "NOMDF", body: "F35_NOMDF" },
    { head: "CAMRERS", body: "F35_CAMRERS" },
    { head: "QRSMES", body: "F35_QRSMES" },
    { head: "QRSPROM", body: "F35_QRSPROM" },
    { head: "CDFVU", body: "F35_CDFVU" },
    { head: "PERADDT", body: "F35_PERADDT" },
    { head: "CDFPC", body: "F35_CDFPC" },
    { head: "INCENTIVO", body: "F35_INCENTIVO" },
    { head: "DISPALT9", body: "F35_DISPALT9" },
    { head: "INCCDFALT9", body: "F35_INCCDFALT9" },
    { head: "VACDFABC", body: "F35_VACDFABC" },
    { head: "VACDF", body: "F35_VACDF" },
    { head: "PRCTCRRCP", body: "F35_PRCTCRRCP" },
    { head: "CDF", body: "F35_CDF" },
    { head: "CDFP", body: "F35_CDFP" },
    { head: "FACCDF", body: "F35_FACCDF" },
    { head: "V0", body: "F35_V0" },
    { head: "VM", body: "F35_VM" },
    { head: "MCRS", body: "F35_MCRS" },
    { head: "ICRSM", body: "F35_ICRSM" },
    { head: "ICCRS", body: "F35_ICCRS" },
    { head: "FREIN", body: "F35_FREIN" },
    { head: "CAPREMDF", body: "F35_CAPREMDF" },
];

export const columnsRevFormato36 = [
    { head: "REVE ID", body: "REVE_ID" },
    { head: "AÑO", body: "F36_ANNO" },
    { head: "MES", body: "F36_MES" },
    { head: "NOMDPTO", body: "F36_NOMDPTO" },
    { head: "NOMMPIO", body: "F36_NOMMPIO" },
    { head: "NOMDF", body: "F36_NOMDF" },
    { head: "VLMES", body: "F36_VLMES" },
    { head: "VLMPROM", body: "F36_VLMPROM" },
    { head: "ESCENA", body: "F36_ESCENA" },
    { head: "CTLMVU", body: "F36_CTLMVU" },
    { head: "ANNOPOSCLA", body: "F36_ANNOPOSCLA" },
    { head: "CTLMPC", body: "F36_CTLMPC" },
    { head: "CTLM", body: "F36_CTLM" },
    { head: "CTLMX", body: "F36_CTLMX" },
    { head: "VACTLABC", body: "F36_VACTLABC" },
    { head: "VACTL", body: "F36_VACTL" },
    { head: "FCKCTL", body: "F36_FCKCTL" },
    { head: "QRS", body: "F36_QRS" },
    { head: "CTL", body: "F36_CTL" },
    { head: "FACCTL", body: "F36_FACCTL" }
];

export const revFormato19 = {
    "REVE_ID": { name: "REVE ID", filtre: true },
    "F19_ANNO": { name: "AÑO", filtre: true },
    "F19_MES": { name: "MES", filtre: true },
    "F19_NJ": { name: "NJ", filtre: false },
    "F19_NDJ": { name: "NDJ", filtre: false },
    "F19_CRTJ": { name: "CRTJ", filtre: false },
    "F19_CDFJ": { name: "CDFJ", filtre: false },
    "F19_QRTJ": { name: "QRTJ", filtre: false },
    "F19_QRJ": { name: "QRJ", filtre: false },
    "F19_QBLJ": { name: "QBLJ", filtre: false },
    "F19_QLUJ": { name: "QLUJ", filtre: false },
    "F19_QNAZ": { name: "QNAZ", filtre: false },
    "F19_QAJ": { name: "QAJ", filtre: false },
};

export const revFormato23 = {
    "REVE_ID": { name: "REVE ID", filtre: true },
    "F23_ANNO": { name: "AÑO", filtre: true },
    "F23_MES": { name: "MES", filtre: true },
    "EMPR_EMPR": { name: "EMPRESAS", filtre: false },
    "F23_ID": { name: "IDNOMAPS", filtre: false },
    "F23_NUAP": { name: "NUAP", filtre: false },
    "F23_N": { name: "N", filtre: false },
    "F23_CP": { name: "CP", filtre: false },
    "F23_CCC": { name: "CCC", filtre: false },
    "F23_M2CCJ": { name: "M2CCJ", filtre: false },
    "F23_CLAVJ": { name: "CLAVJ", filtre: false },
    "F23_M3AGUAJ": { name: "M3AGUAJ", filtre: false },
    "F23_M2LAVJ": { name: "M2LAVJ", filtre: false },
    "F23_CLPJ": { name: "CLPJ", filtre: false },
    "F23_KLPJ": { name: "KLPJ", filtre: false },
    "F23_CCEI": { name: "CCEI", filtre: false },
    "F23_TIJ": { name: "TIJ", filtre: false },
    "F23_CCEMJ": { name: "CCEMJ", filtre: false },
    "F23_TMJ": { name: "TMJ", filtre: false },
    "F23_CLUS": { name: "CLUS", filtre: false },
    "F23_CBLJ": { name: "CBLJ", filtre: false },
    "F23_LBLJ": { name: "LBLJ", filtre: false },
    "F23_CBLS": { name: "CBLS", filtre: false },
    "F23_FACBLCLUS": { name: "FACBLCLUS", filtre: false },
    "F23_ABC": { name: "ABC", filtre: false },
};

export const revFormato24 = {
    "REVE_ID": { name: "REVE ID", filtre: true },
    "F24_ANNO": { name: "AÑO", filtre: true },
    "F24_MES": { name: "MES", filtre: true },
    "F24_NUAP": { name: "NUAP", filtre: false },
    "F24_NUSD": { name: "NUSD", filtre: false },
    "F24_CENTROIDE": { name: "CENTROIDE", filtre: false },
    "F24_QRT": { name: "QRT", filtre: false },
    "F24_F1": { name: "F1", filtre: false },
    "F24_F2": { name: "F2", filtre: false },
    "F24_CPE": { name: "CPE", filtre: false },
    "F24_PRTZ": { name: "PRTZ", filtre: false },
    "F24_DET": { name: "DET", filtre: false },
    "F24_F1ET": { name: "F1ET", filtre: false },
    "F24_CPEET": { name: "CPEET", filtre: false },
    "F24_PRTZET": { name: "PRTZET", filtre: false },
    "F24_CEG": { name: "CEG", filtre: false },
    "F24_CRTP": { name: "CRTP", filtre: false },
    "F24_SALINIDAD": { name: "SALINIDAD", filtre: false },
    "F24_VACRTABC": { name: "VACRTABC", filtre: false },
    "F24_VACRT": { name: "VACRT", filtre: false },
    "F24_FCK": { name: "FCK", filtre: false },
    "F24_T": { name: "T", filtre: false },
    "F24_CRTZ": { name: "CRTZ", filtre: false },
    "F24_CRT": { name: "CRT", filtre: false },
    "F24_FACRT": { name: "FACRT", filtre: false },
    "F24_FACCS": { name: "FACCS", filtre: false },
};

export const revFormato35 = {
    "REVE_ID": { name: "REVE ID", filtre: true },
    "F35_ANNO": { name: "AÑO", filtre: true },
    "F35_MES": { name: "MES", filtre: true },
    "F35_NUSD": { name: "NUSD", filtre: false },
    "F35_NOMDF": { name: "NOMDF", filtre: false },
    "F35_CAMRERS": { name: "CAMRERS", filtre: false },
    "F35_QRSMES": { name: "QRSMES", filtre: false },
    "F35_QRSPROM": { name: "QRSPROM", filtre: false },
    "F35_CDFVU": { name: "CDFVU", filtre: false },
    "F35_PERADDT": { name: "PERADDT", filtre: false },
    "F35_CDFPC": { name: "CDFPC", filtre: false },
    "F35_INCENTIVO": { name: "INCENTIVO", filtre: false },
    "F35_DISPALT9": { name: "DISPALT9", filtre: false },
    "F35_INCCDFALT9": { name: "INCCDFALT9", filtre: false },
    "F35_VACDFABC": { name: "VACDFABC", filtre: false },
    "F35_VACDF": { name: "VACDF", filtre: false },
    "F35_PRCTCRRCP": { name: "PRCTCRRCP", filtre: false },
    "F35_CDF": { name: "CDF", filtre: false },
    "F35_CDFP": { name: "CDFP", filtre: false },
    "F35_FACCDF": { name: "FACCDF", filtre: false },
    "F35_V0": { name: "V0", filtre: false },
    "F35_VM": { name: "VM", filtre: false },
    "F35_MCRS": { name: "MCRS", filtre: false },
    "F35_ICRSM": { name: "ICRSM", filtre: false },
    "F35_ICCRS": { name: "ICCRS", filtre: false },
    "F35_FREIN": { name: "FREIN", filtre: false },
    "F35_CAPREMDF": { name: "CAPREMDF", filtre: false }
};

export const revFormato36 = {
    "REVE_ID": { name: "REVE ID", filtre: true },
    "F36_ANNO": { name: "AÑO", filtre: true },
    "F36_MES": { name: "MES", filtre: true },
    "F36_NUSD": { name: "NUSD", filtre: false },
    "F36_NOMDPTO": { name: "NOMDPTO", filtre: false },
    "F36_NOMMPIO": { name: "NOMMPIO", filtre: false },
    "F36_NOMDF": { name: "NOMDF", filtre: false },
    "F36_VLMES": { name: "VLMES", filtre: false },
    "F36_VLMPROM": { name: "VLMPROM", filtre: false },
    "F36_ESCENA": { name: "ESCENA", filtre: false },
    "F36_CTLMVU": { name: "CTLMVU", filtre: false },
    "F36_ANNOPOSCLA": { name: "ANNOPOSCLA", filtre: false },
    "F36_CTLMPC": { name: "CTLMPC", filtre: false },
    "F36_CTLM": { name: "CTLM", filtre: false },
    "F36_CTLMX": { name: "CTLMX", filtre: false },
    "F36_VACTLABC": { name: "VACTLABC", filtre: false },
    "F36_VACTL": { name: "VACTL", filtre: false },
    "F36_FCKCTL": { name: "FCKCTL", filtre: false },
    "F36_QRS": { name: "QRS", filtre: false },
    "F36_CTL": { name: "CTL", filtre: false },
    "F36_FACCTL": { name: "FACCTL", filtre: false }
};
