export const columsF19 = [
    { head: "NJ", body: "F19_NJ" },
    { head: "NDJ", body: "F19_NDJ" },
    { head: "CRTJ", body: "F19_CRTJ" },
    { head: "CDFJ", body: "F19_CDFJ" },
    { head: "QRTJ", body: "F19_QRTJ" },
    { head: "QRJ", body: "F19_QRJ" },
    { head: "QBLJ", body: "F19_QBLJ" },
    { head: "QLUJ", body: "F19_QLUJ" },
    { head: "QNAZ", body: "F19_QNAZ" },
    { head: "QAJ", body: "F19_QAJ" },
];

export const columsF23 = [
    { head: "Empresas", body: "EMPR_EMPR" },
    { head: "IDNOMAPS", body: "F23_ID" },
    { head: "NUAP", body: "F23_NUAP" },
    { head: "N", body: "F23_N" },
    { head: "CP", body: "F23_CP" },
    { head: "CCC", body: "F23_CCC" },
    { head: "M2CCJ", body: "F23_M2CCJ" },
    { head: "CLAVJ", body: "F23_CLAVJ" },
    { head: "M3AGUAJ", body: "F23_M3AGUAJ" },
    { head: "M2LAVJ", body: "F23_M2LAVJ" },
    { head: "CLPJ", body: "F23_CLPJ" },
    { head: "KLPJ", body: "F23_KLPJ" },
    { head: "CCEI", body: "F23_CCEI" },
    { head: "TIJ", body: "F23_TIJ" },
    { head: "CCEMJ", body: "F23_CCEMJ" },
    { head: "TMJ", body: "F23_TMJ" },
    { head: "CLUS", body: "F23_CLUS" },
    { head: "CBLJ", body: "F23_CBLJ" },
    { head: "LBLJ", body: "F23_LBLJ" },
    { head: "CBLS", body: "F23_CBLS" },
    { head: "FACBLCLUS", body: "F23_FACBLCLUS" },
    { head: "ABC", body: "F23_ABC" },
];

export const columsF24 = [
    { head: "NUAP", body: "F24_NUAP" },
    { head: "NUSD", body: "F24_NUSD" },
    { head: "CENTROIDE", body: "F24_CENTROIDE" },
    { head: "QRT", body: "F24_QRT" },
    { head: "F1", body: "F24_F1" },
    { head: "F2", body: "F24_F2" },
    { head: "CPE", body: "F24_CPE" },
    { head: "PRTZ", body: "F24_PRTZ" },
    { head: "DET", body: "F24_DET" },
    { head: "F1ET", body: "F24_F1ET" },
    { head: "CPEET", body: "F24_CPEET" },
    { head: "PRTZET", body: "F24_PRTZET" },
    { head: "CEG", body: "F24_CEG" },
    { head: "CRTP", body: "F24_CRTP" },
    { head: "SALINIDAD", body: "F24_SALINIDAD" },
    { head: "VACRTABC", body: "F24_VACRTABC" },
    { head: "VACRT", body: "F24_VACRT" },
    { head: "FCK", body: "F24_FCK" },
    { head: "T", body: "F24_T" },
    { head: "CRTZ", body: "F24_CRTZ" },
    { head: "CRT", body: "F24_CRT" },
    { head: "FACRT", body: "F24_FACRT" },
    { head: "FACCS", body: "F24_FACCS" },
];

export const columsF35 = [
    { head: "NUSD", body: "F35_NUSD" },
    { head: "NOMDF", body: "F35_NOMDF" },
    { head: "CAMRERS", body: "F35_CAMRERS" },
    { head: "QRSMES", body: "F35_QRSMES" },
    { head: "QRSPROM", body: "F35_QRSPROM" },
    { head: "CDFVU", body: "F35_CDFVU" },
    { head: "PERADDT", body: "F35_PERADDT" },
    { head: "CDFPC", body: "F35_CDFPC" },
    { head: "INCENTIVO", body: "F35_INCENTIVO" },
    { head: "DISPALT9", body: "F35_DISPALT9" },
    { head: "INCCDFALT9", body: "F35_INCCDFALT9" },
    { head: "VACDFABC", body: "F35_VACDFABC" },
    { head: "VACDF", body: "F35_VACDF" },
    { head: "PRCTCRRCP", body: "F35_PRCTCRRCP" },
    { head: "CDF", body: "F35_CDF" },
    { head: "CDFP", body: "F35_CDFP" },
    { head: "FACCDF", body: "F35_FACCDF" },
    { head: "V0", body: "F35_V0" },
    { head: "VM", body: "F35_VM" },
    { head: "MCRS", body: "F35_MCRS" },
    { head: "ICRSM", body: "F35_ICRSM" },
    { head: "ICCRS", body: "F35_ICCRS" },
    { head: "FREIN", body: "F35_FREIN" },
    { head: "CAPREMDF", body: "F35_CAPREMDF" },
];

export const columsF36 = [
    { head: "NUSD", body: "F36_NUSD" },
    { head: "NOMDPTO", body: "F36_NOMDPTO" },
    { head: "NOMMPIO", body: "F36_NOMMPIO" },
    { head: "NOMDF", body: "F36_NOMDF" },
    { head: "VLMES", body: "F36_VLMES" },
    { head: "VLMPROM", body: "F36_VLMPROM" },
    { head: "ESCENA", body: "F36_ESCENA" },
    { head: "CTLMVU", body: "F36_CTLMVU" },
    { head: "ANNOPOSCLA", body: "F36_ANNOPOSCLA" },
    { head: "CTLMPC", body: "F36_CTLMPC" },
    { head: "CTLM", body: "F36_CTLM" },
    { head: "CTLMX", body: "F36_CTLMX" },
    { head: "VACTLABC", body: "F36_VACTLABC" },
    { head: "VACTL", body: "F36_VACTL" },
    { head: "FCKCTL", body: "F36_FCKCTL" },
    { head: "QRS", body: "F36_QRS" },
    { head: "CTL", body: "F36_CTL" },
    { head: "FACCTL", body: "F36_FACCTL" },
];
