export const columsEnergia = [
    {head: 'Año', body: 'FAEN_ANNO'},
    {head: 'Mes', body: 'FAEN_MES'},
    {head: 'Clase uso', body: 'CLAS_NOMBRE'},
    {head: 'Tipo tarifa', body: 'TIPOTAR'},
    {head: 'Factor prod', body: 'FACTOR_PROD'},
    {head: 'SUB/CON', body: 'FAEN_SUBCON'},
    {head: 'Cant usuarios', body: 'FAEN_USUARIOS'},
    {head: 'TC', body: 'FAEN_TCPROP'},
    {head: 'Tc Aprov Terc', body: 'FAEN_TCTERC'},
    {head: 'TC Aprov Pro', body: 'FAEN_TCAPRO'},
    {head: 'TBL', body: 'FAEN_TBL'},
    {head: 'TLU', body: 'FAEN_TLU'},
    {head: 'TRT', body: 'FAEN_TRT'},
    {head: 'TDF', body: 'FAEN_TDF'},
    {head: 'Tinc', body:'FAEN_TINC'},
    {head: 'Tiat', body: 'FAEN_TIAT'},
    {head: 'TTL', body: 'FAEN_TTL'},
    {head: 'TA', body: 'FAEN_TA'},
    {head: 'Total', body: 'FAEN_TOTAL'},
    {head: 'Total S/C', body: 'FAEN_TOTSC'},
    {head: 'TOT PROP PLENO', body: 'FAEN_TOTPROPLENO'},
    {head: 'TOP PROP S/C', body: 'FAEN_TOTPROSUBCON'},
]

export const columsAcueducto = [
    {head: 'Año', body: 'FACU_ANNO'},
    {head: 'Mes', body: 'FACU_MES'},
    {head: 'Clase uso', body: 'CLAS_NOMBRE'},
    {head: 'Tipo tarifa', body: 'TIPOTAR'},
    {head: 'Factor prod', body: 'FACTOR_PROD'},
    {head: 'SUB/CON', body: 'FACU_SUBCON'},
    {head: 'Cant usuarios', body: 'FACU_USUARIOS'},
    {head: 'TC', body: 'FACU_TCPROP'},
    {head: 'Tc Aprov Terc', body: 'FACU_TCTERC'},
    {head: 'TC Aprov Pro', body: 'FACU_TCAPRO'},
    {head: 'TBL', body: 'FACU_TBL'},
    {head: 'TLU', body: 'FACU_TLU'},
    {head: 'TRT', body: 'FACU_TRT'},
    {head: 'TDF', body: 'FACU_TDF'},
    {head: 'Tinc', body:'FACU_TINC'},
    {head: 'Tiat', body: 'FACU_TIAT'},
    {head: 'TTL', body: 'FACU_TTL'},
    {head: 'TA', body: 'FACU_TA'},
    {head: 'Total', body: 'FACU_TOTAL'},
    {head: 'Total S/C', body: 'FACU_TOTSC'},
    {head: 'TOT PROP PLENO', body: 'FACU_TOTPROPLENO'},
    {head: 'TOP PROP S/C', body: 'FACU_TOTPROSUBCON'},
]

export const columsCostos = [
    {head: 'Año', body: 'COST_ANNO'},
    {head: 'Mes', body: 'COST_MES'},
    {head: 'Tipo factura', body: 'TIPO_FACT'},
    {head: 'CCS', body: 'COST_CCS'},
    {head: 'CSSaprov', body: 'COST_CCSAPRO'},
    {head: 'CBL', body: 'COST_CBL'},
    {head: 'CLUS', body: 'COST_CLUS'},
    {head: 'CRT', body: 'COST_CTR'},
    {head: 'CDF', body: 'COST_CDF'},
    {head: 'INC', body: 'COST_INC'},
    {head: 'IAT', body: 'COST_IAT'},
    {head: 'CTL', body: 'COST_CTL'},
    {head: 'VBA', body: 'COST_VBA'},
]

export const columsTarifa = [
    {head: 'Año', body: 'TARI_ANNO'},
    {head: 'Mes', body: 'TARI_MES'},
    {head: 'Clase uso', body: 'CLAS_NOMBRE'},
    {head: 'Tipo tarifa', body: 'TIPO_TAR'},
    {head: 'Tipo factura', body: 'TIPO_FACT'},
    {head: 'SUB/CON', body: 'TARI_SUBCON'},
    {head: 'TC', body: 'TARI_TCPROP'},
    {head: 'TCaprov', body: 'TARI_TCAPRO'},
    {head: 'TBL', body: 'TARI_TBL'},
    {head: 'TLU', body: 'TARI_TLU'},
    {head: 'TRT', body: 'TARI_TRT'},
    {head: 'TDF', body: 'TARI_TDT'},
    {head: 'Tinc', body: 'TARI_INC'},
    {head: 'Tiat', body: 'TARI_TIAT'},
    {head: 'TTL', body: 'TARI_TTL'},
    {head: 'TA', body: 'TARI_TA'},
    {head: 'TARIFA PLENA', body: 'TARI_TOTAL'},
    {head: 'TARIDA S/C', body: 'TARI_TOTSC'},
]