export const apsService = {

    formato: {
        "APSA_NUAP": false,
        "APSA_IDSUI": true,
        "APSA_ID": false,
        "APSA_NOMAPS": true,
        "APSA_ESTADO": false,
        "APSA_PROPIO": false,
        "APSA_FECHACREACION": false,
        "USUA_USUA": false,
        "EMPR_HOMOLOGACION": false,
        "APSA_EXISTEET": false,
        "APSA_TIPOPROGRESIV": false,
        "APSA_RESOLUCION": false,
        "APSA_VIAT": false,
        "APSA_SOLORELL": false,
        "APSA_DESCRIPCION": false,
    },
    datos: [
        {
            "APSA_NUAP": "0",
            "APSA_IDSUI": "0",
            "APSA_ID": 1,
            "APSA_NOMAPS": "Au costa",
            "APSA_ESTADO": 0,
            "APSA_PROPIO": 1,
            "APSA_FECHACREACION": "2018-01-19",
            "USUA_USUA": 1,
            "EMPR_HOMOLOGACION": 0,
            "APSA_EXISTEET": 0,
            "APSA_TIPOPROGRESIV": 0,
            "APSA_RESOLUCION": 720,
            "APSA_VIAT": 0,
            "APSA_SOLORELL": 0,
            "APSA_DESCRIPCION": "AU COSTA1"
        },
        {
            "APSA_NUAP": "0",
            "APSA_IDSUI": "0",
            "APSA_ID": 100,
            "APSA_NOMAPS": "Promo",
            "APSA_ESTADO": 0,
            "APSA_PROPIO": 0,
            "APSA_FECHACREACION": "2018-03-16",
            "USUA_USUA": 1,
            "EMPR_HOMOLOGACION": 0,
            "APSA_EXISTEET": 0,
            "APSA_TIPOPROGRESIV": 0,
            "APSA_RESOLUCION": 720,
            "APSA_VIAT": 0,
            "APSA_SOLORELL": 0,
            "APSA_DESCRIPCION": "PROMO"
        },
        {
            "APSA_NUAP": "366154001",
            "APSA_IDSUI": "2866",
            "APSA_ID": 1001,
            "APSA_NOMAPS": "SUR",
            "APSA_ESTADO": 0,
            "APSA_PROPIO": 1,
            "APSA_FECHACREACION": "2020-03-16",
            "USUA_USUA": 1,
            "EMPR_HOMOLOGACION": 0,
            "APSA_EXISTEET": 0,
            "APSA_TIPOPROGRESIV": 0,
            "APSA_RESOLUCION": 720,
            "APSA_VIAT": 1,
            "APSA_SOLORELL": 0,
            "APSA_DESCRIPCION": "cucuta sur"
        }
    ]
}