export const columnsCrear = [
    { head: "Id Proy", body: "PROYID" },
    { head: "Aps", body: "APSA_NOMAPS" },
    { head: "Nombre", body: "PROYNOMBRE" },
    { head: "Descripción", body: "PROYDESCRIPCION" },
    { head: "Tipo Proy", body: "PARA_NOMBRE" },
    { head: "Desde", body: "DESDE" },
    { head: "Horizonte Hasta", body: "HASTA" },
    { head: "Usuario", body: "SISU_CORREO" },
];

export const formatoCrear = {
    'PROYID': { name: 'Id Proy', filtre: true },
    'APSA_NOMAPS': { name: 'Aps', filtre: true },
    'PROYNOMBRE': { name: 'Nombre', filtre: false },
    'PROYDESCRIPCION': { name: 'Descripción', filtre: false },
    'PARA_NOMBRE': { name: 'Tipo Proy', filtre: true },
    'DESDE': { name: 'Desde', filtre: false },
    'HASTA': { name: 'Horizonte Hasta', filtre: false },
    'SISU_CORREO': { name: 'Usuario', filtre: true },
};

export const columnsSubContri = [
    { head: "clase de uso", body: "CLAS_CLASE" },
    { head: "valor", body: "SUCO_VALOR" },
];

export const columnsLineasTimp = [
    { head: "AÑO", body: "PROYANNO" },
    { head: "MES", body: "PROYMES" },
    { head: "IPC", body: "DELTIPC" },
    { head: "IPCC", body: "DELTIPCC" },
    { head: "SMLV", body: "DELTSMLV" },
    { head: "IOEXP", body: "DELTIOEXP" },
    { head: "FACT PROD", body: "DELTFACPRODUC" },
    { head: "IND", body: "DELTINDIPCC" },
];

export const columsLineasTiempo = [
    { head: "AÑO", body: "PROYANNO" },
    { head: "MES", body: "PROYMES" },
    { head: "IPC", body: "DELTIPC" },
    { head: "IPCC", body: "DELTIPCC" },
    { head: "SMLV", body: "DELTSMLV" },
    { head: "IOEXP", body: "DELTIOEXP" },
    { head: "FACT PROD", body: "DELTFACPRODUC" },
    { head: "IND IPCC", body: "DELTINDIPCC" },
];

export const columsUsuarioVariables = [
    { head: "APS", body: "COD_APS" },
    { head: "AÑO", body: "ANNO" },
    { head: "SEMESTRE", body: "SEMESTRE" },
    { head: "COD_USO", body: "CODUSO" },
    { head: "CLASE_USO", body: "NOMCLASEUSO" },
    { head: "COD_FACTOR", body: "CODFACTOR" },
    { head: "VLR_FACTOR", body: "VALORFACTOR" },
    { head: "COD_TIPRED", body: "CODTIPOPRED" },
    { head: "TIPO_PRED", body: "NOMTIPOPRED" },
    { head: "CANTIDAD", body: "CANTIDAD" },
    { head: "TONELADAS", body: "TONELADAS" },
  ];

  export const columnsPropiaVariables = [
    { head: "COD_APS", body: "COD_APS" },
    { head: "NOM_APS", body: "NOM_APS" },
    { head: "COD_EMPRESA", body: "COD_EMPRESA" },
    { head: "NOM_EMPRESA", body: "NOM_EMPRESA" },
    { head: "AÑO", body: "ANNO" },
    { head: "MES", body: "MES" },
    { head: "V_DISPTERC", body: "V_DISPTERC" },
    { head: "IAT", body: "IAT" },
    { head: "V_N", body: "V_N" },
    { head: "V_NA", body: "V_NA" },
    { head: "V_ND", body: "V_ND" },
    { head: "V_TAFNA", body: "V_TAFNA" },
    { head: "V_QRT", body: "V_QRT" },
    { head: "V_QLU", body: "V_QLU" },
    { head: "V_QNA", body: "V_QNA" },
    { head: "V_QBL", body: "V_QBL" },
    { head: "V_QR", body: "V_QR" },
    { head: "V_QRS", body: "V_QRS" },
    { head: "V_CBLJ", body: "V_CBLJ" },
    { head: "V_LBL", body: "V_LBL" },
    { head: "V_VALOR_MTS3", body: "V_VALOR_MTS3" },
    { head: "V_M2CC", body: "V_M2CC" },
    { head: "V_M2LAV", body: "V_M2LAV" },
    { head: "V_TI", body: "V_TI" },
    { head: "V_TM", body: "V_TM" },
    { head: "V_KLP", body: "V_KLP" },
    { head: "V_VL", body: "V_VL" },
    { head: "V_ESCENARIO", body: "V_ESCENARIO" },
    { head: "V_CTLMX", body: "V_CTLMX" },
    { head: "V_T", body: "V_T" },
    { head: "V_CPE", body: "V_CPE" },
    { head: "V_VA_CRT", body: "V_VA_CRT" },
    { head: "V_VA_CRT_ABC", body: "V_VA_CRT_ABC" },
    { head: "V_VA_CDF", body: "V_VA_CDF" },
    { head: "V_VA_CDF_ABC", body: "V_VA_CDF_ABC" },
    { head: "V_QA", body: "V_QA" },
    { head: "V_TAFA", body: "V_TAFA" },
    { head: "V_CP", body: "V_CP" },
    { head: "V_CRT_PROPIO", body: "V_CRT_PROPIO" },
    { head: "V_CDF_FACTURADO", body: "V_CDF_FACTURADO" },
    { head: "V_QRTZ", body: "V_QRTZ" },
    { head: "V_CDF_TERCERO", body: "V_CDF_TERCERO" },
    { head: "V_CTL_TERCERO", body: "V_CTL_TERCERO" },
    { head: "V_IR_TERCERO", body: "V_IR_TERCERO" },
  ];
  
  export const columsTercerosVariables = [
    { head: "COD_APS", body: "COD_APS" },
    { head: "NOM_APS", body: "NOM_APS" },
    { head: "COD_EMPRESA", body: "COD_EMPRESA" },
    { head: "NOM_EMPRESA", body: "NOM_EMPRESA" },
    { head: "ANNO", body: "ANNO" },
    { head: "MES", body: "MES" },
    { head: "C_N", body: "C_N" },
    { head: "C_NA", body: "C_NA" },
    { head: "C_ND", body: "C_ND" },
    { head: "C_TAFNA", body: "C_TAFNA" },
    { head: "C_VALOR_MTS3", body: "C_VALOR_MTS3" },
    { head: "C_QRT", body: "C_QRT" },
    { head: "C_QLU", body: "C_QLU" },
    { head: "C_QNA", body: "C_QNA" },
    { head: "C_QBL", body: "C_QBL" },
    { head: "C_QRECHAZO", body: "C_QRECHAZO" },
    { head: "C_QRS", body: "C_QRS" },
    { head: "C_CBLJ", body: "C_CBLJ" },
    { head: "C_LBL", body: "C_LBL" },
    { head: "C_M2CC", body: "C_M2CC" },
    { head: "C_M2LAV", body: "C_M2LAV" },
    { head: "C_TI", body: "C_TI" },
    { head: "C_TM", body: "C_TM" },
    { head: "C_KLP", body: "C_KLP" },
    { head: "C_VL", body: "C_VL" },
    { head: "C_ESCENARIO", body: "C_ESCENARIO" },
    { head: "C_T", body: "C_T" },
    { head: "C_CPE", body: "C_CPE" },
    { head: "C_CTLMX", body: "C_CTLMX" },
    { head: "C_VA_CRT", body: "C_VA_CRT" },
    { head: "C_VA_CRT_ABC", body: "C_VA_CRT_ABC" },
    { head: "C_VA_CDF", body: "C_VA_CDF" },
    { head: "C_VA_CDF_ABC", body: "C_VA_CDF_ABC" },
    { head: "C_QA", body: "C_QA" },
    { head: "C_TAFA", body: "C_TAFA" },
    { head: "C_CRT_COMPETIDOR", body: "C_CRT_COMPETIDOR" },
    { head: "C_CDF_COMPETIDOR", body: "C_CDF_COMPETIDOR" },
    { head: "C_QRTZ", body: "C_QRTZ" },
    { head: "C_CTL_SIN_INCENTIVO", body: "C_CTL_SIN_INCENTIVO" },
    { head: "C_INCENTIVO", body: "C_INCENTIVO" },
    { head: "C_CDFSINCENTIVO", body: "C_CDFSINCENTIVO" },
    { head: "C_CPODA", body: "C_CPODA" }, 
  ];
  