export const columnsPropia = [
    { head: "APS", body: "aps" },
    { head: "EMPRESA", body: "empr" },
    { head: "AÑO", body: "anno" },
    { head: "MES", body: "mes" },
    { head: "QRT", body: "qrt" },
    { head: "QLU", body: "qlu" },
    { head: "QNA", body: "qna" },
    { head: "QBL", body: "qbl" },
    { head: "QR", body: "qr" },
    { head: "QRS", body: "qrs" },
    { head: "LBL", body: "lbl" },
    { head: "VL", body: "vl" },
    { head: "ESCE", body: "esce" },
    { head: "CTLMX", body: "ctlmx" },
    { head: "CPE", body: "cpe" },
    { head: "NAA", body: "naa" },
    { head: "TAFA", body: "tafa" },
    { head: "CRTPRO", body: "crtpro" },
    { head: "CDFPRO", body: "cdfpro" },
  ];