export const columnsPropiaSem = [
    { head: "APS", body: "aps" },
    { head: "EMPRESA", body: "empr" },
    { head: "AÑO", body: "anno" },
    { head: "MES", body: "mes" },
    { head: "QRT", body: "qrt" },
    { head: "QLU", body: "qlu" },
    { head: "QNA", body: "qna" },
    { head: "QBL", body: "qbl" },
    { head: "QR", body: "qr" },
    { head: "QRS", body: "qrs" },
    { head: "LBL", body: "lbl" },
    { head: "VL", body: "vl" },
    { head: "ESCE", body: "esce" },
    { head: "CTLMX", body: "ctlmx" },
    { head: "CPE", body: "cpe" },
    { head: "NAA", body: "naa" },
    { head: "TAFA", body: "tafa" },
    { head: "CRTPRO", body: "crtpro" },
    { head: "CDFPRO", body: "cdfpro" },
  ];

  export const columnsCompetidorSem = [
    { head: "APS", body: "aps" },
    { head: "EMPRESA", body: "empr" },
    { head: "AÑO", body: "anno" },
    { head: "MES", body: "mes" },
    { head: "N", body: "n" },
    { head: "NA", body: "na" },
    { head: "ND", body: "nd" },
    { head: "QLU", body: "qlu" },
    { head: "QNA", body: "qna" },
    { head: "QBL", body: "qbl" },
    { head: "QR", body: "qr" },
    { head: "CBLJ", body: "cblj" },
    { head: "LBL", body: "lbl" },
    { head: "CRTCOMP", body: "crtcomp" },
    { head: "CDFCOMP", body: "cdfcomp" },
    { head: "QRTZ", body: "qrtz" }
];

export const columnsUsuarioSem = [
    { head: "Cod. Aps", body: "codaps" },
    { head: "APS", body: "aps" },
    { head: "Año", body: "anno" },
    { head: "Semestre", body: "semestre" },
    { head: "Cod. CU", body: "coduso" },
    { head: "Nombre CU", body: "nomuso" },
    { head: "Cod. Factor", body: "codfactor" },
    { head: "Nom. Factor", body: "nomfact" },
    { head: "Cod. Tipo", body: "codtipo" },
    { head: "Nom. Tipo", body: "nomtipo" },
    { head: "Sus M1", body: "susm1" },
    { head: "Sus M2", body: "susm2" },
    { head: "Sus M3", body: "susm3" },
    { head: "Sus M4", body: "susm4" },
    { head: "Sus M5", body: "susm5" },
    { head: "Sus M6", body: "susm6" },
    { head: "Afo M1", body: "afom1" },
    { head: "Afo M2", body: "afom2" },
    { head: "Afo M3", body: "afom3" },
    { head: "Afo M4", body: "afom4" },
    { head: "Afo M5", body: "afom5" },
    { head: "Afo M6", body: "afom6" }
  ];
  

export const columnsPropiaMen = [
    { head: "APS", body: "aps" },
    { head: "EMPRESA", body: "empr" },
    { head: "AÑO", body: "anno" },
    { head: "MES", body: "mes" },
    { head: "CP", body: "cp" },
    { head: "MT3AGUA", body: "mt3agua" },
    { head: "M2CC", body: "m2cc" },
    { head: "M2LAV", body: "m2lav" },
    { head: "TI", body: "ti" },
    { head: "TM", body: "tm" },
    { head: "KLP", body: "klp" },
    { head: "T", body: "t" },
    { head: "QA", body: "qa" },
    { head: "ESCENARIO", body: "escenario" }
];

export const columnsCompetidorMen = [
    { head: "APS", body: "aps" },
    { head: "EMPRESA", body: "empr" },
    { head: "AÑO", body: "anno" },
    { head: "MES", body: "mes" },
    { head: "CP", body: "cp" },
    { head: "MT3AGUA", body: "mt3agua" },
    { head: "M2CC", body: "m2cc" },
    { head: "M2LAV", body: "m2lav" },
    { head: "TI", body: "ti" },
    { head: "TM", body: "tm" },
    { head: "KLP", body: "klp" },
    { head: "CBLJ", body: "cblj" },
];